# Generated by Django 5.0.2 on 2025-12-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintrack2_api', '0003_category_budget_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#34495e', max_length=20),
        ),
    ]
