# Generated by Django 5.0.2 on 2025-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fintrack2_api', '0004_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre opcional para el presupuesto', max_length=100, null=True),
        ),
    ]
