# Generated by Django 5.0.2 on 2025-12-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fintrack2_api', '0005_budget_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'periodo')},
        ),
    ]
