# Generated by Django 5.0.2 on 2025-12-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fintrack2_api', '0006_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category')},
        ),
    ]
