# Generated by Django 5.0.2 on 2025-12-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fintrack2_api', '0007_alter_budget_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='nombre',
        ),
    ]
